/*
 * This file is generated by jOOQ.
 */
package ch.countryname.countrygame.db.tables.daos


import ch.countryname.countrygame.db.tables.Country
import ch.countryname.countrygame.db.tables.records.CountryRecord

import java.lang.Integer
import java.lang.String
import java.util.List

import org.jooq.Configuration
import org.jooq.impl.DAOImpl


class CountryDao(configuration : Configuration) extends DAOImpl[CountryRecord, ch.countryname.countrygame.db.tables.pojos.Country, Integer](Country.COUNTRY, classOf[ch.countryname.countrygame.db.tables.pojos.Country], configuration) {

  def this() = {
    this(null)
  }

  override protected def getId(o : ch.countryname.countrygame.db.tables.pojos.Country) : Integer = {
    o.getCountryid
  }

  def fetchByCountryid(values : Integer*) : List[ch.countryname.countrygame.db.tables.pojos.Country] = {
    fetch(Country.COUNTRY.COUNTRYID, values:_*)
  }

  def fetchOneByCountryid(value : Integer) : ch.countryname.countrygame.db.tables.pojos.Country = {
    fetchOne(Country.COUNTRY.COUNTRYID, value)
  }

  def fetchByCountryname(values : String*) : List[ch.countryname.countrygame.db.tables.pojos.Country] = {
    fetch(Country.COUNTRY.COUNTRYNAME, values:_*)
  }

  def fetchByCountrydetails(values : String*) : List[ch.countryname.countrygame.db.tables.pojos.Country] = {
    fetch(Country.COUNTRY.COUNTRYDETAILS, values:_*)
  }

  def fetchByCountrycode(values : String*) : List[ch.countryname.countrygame.db.tables.pojos.Country] = {
    fetch(Country.COUNTRY.COUNTRYCODE, values:_*)
  }

  def fetchByCurrencyid(values : Integer*) : List[ch.countryname.countrygame.db.tables.pojos.Country] = {
    fetch(Country.COUNTRY.CURRENCYID, values:_*)
  }

  def fetchByManpowerid(values : Integer*) : List[ch.countryname.countrygame.db.tables.pojos.Country] = {
    fetch(Country.COUNTRY.MANPOWERID, values:_*)
  }

  def fetchByModifierid(values : Integer*) : List[ch.countryname.countrygame.db.tables.pojos.Country] = {
    fetch(Country.COUNTRY.MODIFIERID, values:_*)
  }
}
