/*
 * This file is generated by jOOQ.
 */
package ch.countryname.countrygame.db.tables.daos


import ch.countryname.countrygame.db.tables.Currency
import ch.countryname.countrygame.db.tables.records.CurrencyRecord

import java.lang.Integer
import java.lang.String
import java.util.List

import org.jooq.Configuration
import org.jooq.impl.DAOImpl


class CurrencyDao(configuration : Configuration) extends DAOImpl[CurrencyRecord, ch.countryname.countrygame.db.tables.pojos.Currency, Integer](Currency.CURRENCY, classOf[ch.countryname.countrygame.db.tables.pojos.Currency], configuration) {

  def this() = {
    this(null)
  }

  override protected def getId(o : ch.countryname.countrygame.db.tables.pojos.Currency) : Integer = {
    o.getCurrencyid
  }

  def fetchByCurrencyid(values : Integer*) : List[ch.countryname.countrygame.db.tables.pojos.Currency] = {
    fetch(Currency.CURRENCY.CURRENCYID, values:_*)
  }

  def fetchOneByCurrencyid(value : Integer) : ch.countryname.countrygame.db.tables.pojos.Currency = {
    fetchOne(Currency.CURRENCY.CURRENCYID, value)
  }

  def fetchByCurrencyname(values : String*) : List[ch.countryname.countrygame.db.tables.pojos.Currency] = {
    fetch(Currency.CURRENCY.CURRENCYNAME, values:_*)
  }

  def fetchByCurrencycountryid(values : Integer*) : List[ch.countryname.countrygame.db.tables.pojos.Currency] = {
    fetch(Currency.CURRENCY.CURRENCYCOUNTRYID, values:_*)
  }

  def fetchByCurrencycountryname(values : Integer*) : List[ch.countryname.countrygame.db.tables.pojos.Currency] = {
    fetch(Currency.CURRENCY.CURRENCYCOUNTRYNAME, values:_*)
  }
}
