/*
 * This file is generated by jOOQ.
 */
package ch.countryname.countrygame.db.tables.daos


import ch.countryname.countrygame.db.tables.Relationtypes
import ch.countryname.countrygame.db.tables.records.RelationtypesRecord

import java.lang.Integer
import java.lang.String
import java.util.List

import org.jooq.Configuration
import org.jooq.impl.DAOImpl


class RelationtypesDao(configuration : Configuration) extends DAOImpl[RelationtypesRecord, ch.countryname.countrygame.db.tables.pojos.Relationtypes, Integer](Relationtypes.RELATIONTYPES, classOf[ch.countryname.countrygame.db.tables.pojos.Relationtypes], configuration) {

  def this() = {
    this(null)
  }

  override protected def getId(o : ch.countryname.countrygame.db.tables.pojos.Relationtypes) : Integer = {
    o.getRelationtypeid
  }

  def fetchByRelationtypeid(values : Integer*) : List[ch.countryname.countrygame.db.tables.pojos.Relationtypes] = {
    fetch(Relationtypes.RELATIONTYPES.RELATIONTYPEID, values:_*)
  }

  def fetchOneByRelationtypeid(value : Integer) : ch.countryname.countrygame.db.tables.pojos.Relationtypes = {
    fetchOne(Relationtypes.RELATIONTYPES.RELATIONTYPEID, value)
  }

  def fetchByRelationtype(values : String*) : List[ch.countryname.countrygame.db.tables.pojos.Relationtypes] = {
    fetch(Relationtypes.RELATIONTYPES.RELATIONTYPE, values:_*)
  }

  def fetchByRelationtypedescription(values : String*) : List[ch.countryname.countrygame.db.tables.pojos.Relationtypes] = {
    fetch(Relationtypes.RELATIONTYPES.RELATIONTYPEDESCRIPTION, values:_*)
  }
}
