/*
 * This file is generated by jOOQ.
 */
package ch.countryname.countrygame.db.tables.daos


import ch.countryname.countrygame.db.tables.Relations
import ch.countryname.countrygame.db.tables.records.RelationsRecord

import java.lang.Integer
import java.util.List

import org.jooq.Configuration
import org.jooq.impl.DAOImpl


class RelationsDao(configuration : Configuration) extends DAOImpl[RelationsRecord, ch.countryname.countrygame.db.tables.pojos.Relations, Integer](Relations.RELATIONS, classOf[ch.countryname.countrygame.db.tables.pojos.Relations], configuration) {

  def this() = {
    this(null)
  }

  override protected def getId(o : ch.countryname.countrygame.db.tables.pojos.Relations) : Integer = {
    o.getRelationid
  }

  def fetchByRelationid(values : Integer*) : List[ch.countryname.countrygame.db.tables.pojos.Relations] = {
    fetch(Relations.RELATIONS.RELATIONID, values:_*)
  }

  def fetchOneByRelationid(value : Integer) : ch.countryname.countrygame.db.tables.pojos.Relations = {
    fetchOne(Relations.RELATIONS.RELATIONID, value)
  }

  def fetchByCountryid1(values : Integer*) : List[ch.countryname.countrygame.db.tables.pojos.Relations] = {
    fetch(Relations.RELATIONS.COUNTRYID1, values:_*)
  }

  def fetchOneByCountryid1(value : Integer) : ch.countryname.countrygame.db.tables.pojos.Relations = {
    fetchOne(Relations.RELATIONS.COUNTRYID1, value)
  }

  def fetchByRelationtype(values : Integer*) : List[ch.countryname.countrygame.db.tables.pojos.Relations] = {
    fetch(Relations.RELATIONS.RELATIONTYPE, values:_*)
  }
}
