/*
 * This file is generated by jOOQ.
 */
package ch.countryname.countrygame.db.tables.pojos


import java.io.Serializable
import java.lang.Integer
import java.lang.String
import java.lang.StringBuilder


case class Country(
    countryid : Integer
  , countryname : String
  , countrydetails : String
  , countrycode : String
  , currencyid : Integer
  , modifierid : Integer
) extends Serializable {

  def this (value : Country) = {
    this(
        value.countryid
      , value.countryname
      , value.countrydetails
      , value.countrycode
      , value.currencyid
      , value.modifierid
    )
  }

  def getCountryid : Integer = {
    this.countryid
  }

  def getCountryname : String = {
    this.countryname
  }

  def getCountrydetails : String = {
    this.countrydetails
  }

  def getCountrycode : String = {
    this.countrycode
  }

  def getCurrencyid : Integer = {
    this.currencyid
  }

  def getModifierid : Integer = {
    this.modifierid
  }

  override def toString : String = {
    val sb = new StringBuilder("Country (")

    sb.append(countryid)
    sb.append(", ").append(countryname)
    sb.append(", ").append(countrydetails)
    sb.append(", ").append(countrycode)
    sb.append(", ").append(currencyid)
    sb.append(", ").append(modifierid)

    sb.append(")")
    return sb.toString
  }
}
