/*
 * This file is generated by jOOQ.
 */
package ch.countryname.countrygame.db.tables.pojos


import java.io.Serializable
import java.lang.Double
import java.lang.Integer
import java.lang.StringBuilder


case class Manpower(
    manpowerid : Integer
  , manpowernumber : Double
) extends Serializable {

  def this (value : Manpower) = {
    this(
        value.manpowerid
      , value.manpowernumber
    )
  }

  def getManpowerid : Integer = {
    this.manpowerid
  }

  def getManpowernumber : Double = {
    this.manpowernumber
  }

  override def toString : String = {
    val sb = new StringBuilder("Manpower (")

    sb.append(manpowerid)
    sb.append(", ").append(manpowernumber)

    sb.append(")")
    return sb.toString
  }
}
