/*
 * This file is generated by jOOQ.
 */
package ch.countryname.countrygame.db.tables.pojos


import java.io.Serializable
import java.lang.Double
import java.lang.Integer
import java.lang.String
import java.lang.StringBuilder


case class Modifier(
    modifierid : Integer
  , modifiername : String
  , modifiervalue : Double
) extends Serializable {

  def this (value : Modifier) = {
    this(
        value.modifierid
      , value.modifiername
      , value.modifiervalue
    )
  }

  def getModifierid : Integer = {
    this.modifierid
  }

  def getModifiername : String = {
    this.modifiername
  }

  def getModifiervalue : Double = {
    this.modifiervalue
  }

  override def toString : String = {
    val sb = new StringBuilder("Modifier (")

    sb.append(modifierid)
    sb.append(", ").append(modifiername)
    sb.append(", ").append(modifiervalue)

    sb.append(")")
    return sb.toString
  }
}
