/*
 * This file is generated by jOOQ.
 */
package ch.countryname.countrygame.db.tables.pojos


import java.io.Serializable
import java.lang.Integer
import java.lang.StringBuilder


case class Relations(
    relationid : Integer
  , countryid1 : Integer
  , countryid2 : Integer
  , relationtype : Integer
) extends Serializable {

  def this (value : Relations) = {
    this(
        value.relationid
      , value.countryid1
      , value.countryid2
      , value.relationtype
    )
  }

  def getRelationid : Integer = {
    this.relationid
  }

  def getCountryid1 : Integer = {
    this.countryid1
  }

  def getCountryid2 : Integer = {
    this.countryid2
  }

  def getRelationtype : Integer = {
    this.relationtype
  }

  override def toString : String = {
    val sb = new StringBuilder("Relations (")

    sb.append(relationid)
    sb.append(", ").append(countryid1)
    sb.append(", ").append(countryid2)
    sb.append(", ").append(relationtype)

    sb.append(")")
    return sb.toString
  }
}
