/*
 * This file is generated by jOOQ.
 */
package ch.countryname.countrygame.db.tables.records


import ch.countryname.countrygame.db.tables.Relationtypes

import java.lang.Integer
import java.lang.String

import org.jooq.Field
import org.jooq.Record1
import org.jooq.Record3
import org.jooq.Row3
import org.jooq.impl.UpdatableRecordImpl


class RelationtypesRecord extends UpdatableRecordImpl[RelationtypesRecord](Relationtypes.RELATIONTYPES) with Record3[Integer, String, String] {

  def setRelationtypeid(value : Integer) : Unit = {
    set(0, value)
  }

  def getRelationtypeid : Integer = {
    val r = get(0)
    if (r == null) null else r.asInstanceOf[Integer]
  }

  def setRelationtype(value : String) : Unit = {
    set(1, value)
  }

  def getRelationtype : String = {
    val r = get(1)
    if (r == null) null else r.asInstanceOf[String]
  }

  def setRelationtypedescription(value : String) : Unit = {
    set(2, value)
  }

  def getRelationtypedescription : String = {
    val r = get(2)
    if (r == null) null else r.asInstanceOf[String]
  }

  // -------------------------------------------------------------------------
  // Primary key information
  // -------------------------------------------------------------------------
  override def key : Record1[Integer] = {
    return super.key.asInstanceOf[ Record1[Integer] ]
  }

  // -------------------------------------------------------------------------
  // Record3 type implementation
  // -------------------------------------------------------------------------

  override def fieldsRow : Row3[Integer, String, String] = {
    super.fieldsRow.asInstanceOf[ Row3[Integer, String, String] ]
  }

  override def valuesRow : Row3[Integer, String, String] = {
    super.valuesRow.asInstanceOf[ Row3[Integer, String, String] ]
  }
  override def field1 : Field[Integer] = Relationtypes.RELATIONTYPES.RELATIONTYPEID
  override def field2 : Field[String] = Relationtypes.RELATIONTYPES.RELATIONTYPE
  override def field3 : Field[String] = Relationtypes.RELATIONTYPES.RELATIONTYPEDESCRIPTION
  override def component1 : Integer = getRelationtypeid
  override def component2 : String = getRelationtype
  override def component3 : String = getRelationtypedescription
  override def value1 : Integer = getRelationtypeid
  override def value2 : String = getRelationtype
  override def value3 : String = getRelationtypedescription

  override def value1(value : Integer) : RelationtypesRecord = {
    setRelationtypeid(value)
    this
  }

  override def value2(value : String) : RelationtypesRecord = {
    setRelationtype(value)
    this
  }

  override def value3(value : String) : RelationtypesRecord = {
    setRelationtypedescription(value)
    this
  }

  override def values(value1 : Integer, value2 : String, value3 : String) : RelationtypesRecord = {
    this.value1(value1)
    this.value2(value2)
    this.value3(value3)
    this
  }

  def this(relationtypeid : Integer, relationtype : String, relationtypedescription : String) = {
    this()

    set(0, relationtypeid)
    set(1, relationtype)
    set(2, relationtypedescription)
  }
}
