/*
 * This file is generated by jOOQ.
 */
package ch.countryname.countrygame.db


import java.util.ArrayList
import java.util.Arrays
import java.util.List

import org.jooq.Schema
import org.jooq.impl.CatalogImpl


object DefaultCatalog {

  val DEFAULT_CATALOG = new DefaultCatalog
}

class DefaultCatalog extends CatalogImpl("") {

  val COUNTRY_GAME = ch.countryname.countrygame.db.CountryGame.COUNTRY_GAME

  override def getSchemas : List[Schema] = {
    val result = new ArrayList[Schema]
    result.addAll(getSchemas0)
    result
  }

  private def getSchemas0(): List[Schema] = {
    return Arrays.asList[Schema](
      CountryGame.COUNTRY_GAME)
  }
}
