/*
 * This file is generated by jOOQ.
 */
package ch.countryname.countrygame.db


import ch.countryname.countrygame.db.tables.Country
import ch.countryname.countrygame.db.tables.Currency
import ch.countryname.countrygame.db.tables.FlywaySchemaHistory
import ch.countryname.countrygame.db.tables.Manpower
import ch.countryname.countrygame.db.tables.Modifier
import ch.countryname.countrygame.db.tables.Relations

import java.util.ArrayList
import java.util.Arrays
import java.util.List

import org.jooq.Catalog
import org.jooq.Table
import org.jooq.impl.SchemaImpl


object CountryGame {

  val COUNTRY_GAME = new CountryGame
}

class CountryGame extends SchemaImpl("country_game", DefaultCatalog.DEFAULT_CATALOG) {

  override def getCatalog : Catalog = DefaultCatalog.DEFAULT_CATALOG

  override def getTables : List[Table[_]] = {
    val result = new ArrayList[Table[_]]
    result.addAll(getTables0)
    result
  }

  private def getTables0(): List[Table[_]] = {
    return Arrays.asList[Table[_]](
      Country.COUNTRY,
      Currency.CURRENCY,
      FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY,
      Manpower.MANPOWER,
      Modifier.MODIFIER,
      Relations.RELATIONS)
  }
}
