/*
 * This file is generated by jOOQ.
 */
package ch.countryname.countrygame.db



object Tables {

  val COUNTRY = ch.countryname.countrygame.db.tables.Country.COUNTRY

  val FLYWAY_SCHEMA_HISTORY = ch.countryname.countrygame.db.tables.FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY

  val RELATIONS = ch.countryname.countrygame.db.tables.Relations.RELATIONS

  val RELATIONTYPES = ch.countryname.countrygame.db.tables.Relationtypes.RELATIONTYPES
}
