/*
 * This file is generated by jOOQ.
 */
package ch.countryname.countrygame.db



object Tables {

  val COUNTRY = ch.countryname.countrygame.db.tables.Country.COUNTRY

  val CURRENCY = ch.countryname.countrygame.db.tables.Currency.CURRENCY

  val FLYWAY_SCHEMA_HISTORY = ch.countryname.countrygame.db.tables.FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY

  val MANPOWER = ch.countryname.countrygame.db.tables.Manpower.MANPOWER

  val RELATIONS = ch.countryname.countrygame.db.tables.Relations.RELATIONS
}
