/*
 * This file is generated by jOOQ.
 */
package ch.countryname.countrygame.db.tables


import ch.countryname.countrygame.db.CountryGame
import ch.countryname.countrygame.db.Indexes
import ch.countryname.countrygame.db.Keys
import ch.countryname.countrygame.db.tables.records.CurrencyRecord

import java.lang.Class
import java.lang.Integer
import java.lang.String
import java.util.Arrays
import java.util.List

import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Identity
import org.jooq.Index
import org.jooq.Name
import org.jooq.Record
import org.jooq.Schema
import org.jooq.Table
import org.jooq.TableField
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.TableImpl

import scala.Array


object Currency {

  val CURRENCY = new Currency
}

class Currency(
  alias : Name,
  child : Table[_ <: Record],
  path : ForeignKey[_ <: Record, CurrencyRecord],
  aliased : Table[CurrencyRecord],
  parameters : Array[ Field[_] ]
)
extends TableImpl[CurrencyRecord](
  alias,
  CountryGame.COUNTRY_GAME,
  child,
  path,
  aliased,
  parameters,
  DSL.comment("")
)
{

  override def getRecordType : Class[CurrencyRecord] = {
    classOf[CurrencyRecord]
  }

  val CURRENCYID : TableField[CurrencyRecord, Integer] = createField("currencyId", org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), "")

  val CURRENCYNAME : TableField[CurrencyRecord, String] = createField("currencyName", org.jooq.impl.SQLDataType.VARCHAR(45).nullable(false), "")

  val CURRENCYCOUNTRYID : TableField[CurrencyRecord, Integer] = createField("currencyCountryId", org.jooq.impl.SQLDataType.INTEGER.nullable(false), "")

  val CURRENCYCOUNTRYNAME : TableField[CurrencyRecord, Integer] = createField("currencyCountryName", org.jooq.impl.SQLDataType.INTEGER.nullable(false), "")

  def this() = {
    this(DSL.name("currency"), null, null, null, null)
  }

  def this(alias : String) = {
    this(DSL.name(alias), null, null, ch.countryname.countrygame.db.tables.Currency.CURRENCY, null)
  }

  def this(alias : Name) = {
    this(alias, null, null, ch.countryname.countrygame.db.tables.Currency.CURRENCY, null)
  }

  private def this(alias : Name, aliased : Table[CurrencyRecord]) = {
    this(alias, null, null, aliased, null)
  }

  def this(child : Table[_ <: Record], key : ForeignKey[_ <: Record, CurrencyRecord]) = {
    this(Internal.createPathAlias(child, key), child, key, ch.countryname.countrygame.db.tables.Currency.CURRENCY, null)
  }

  override def getSchema : Schema = CountryGame.COUNTRY_GAME

  override def getIndexes : List[ Index ] = {
    return Arrays.asList[ Index ](Indexes.CURRENCY_CURRENCYCOUNTRYID, Indexes.CURRENCY_PRIMARY)
  }

  override def getIdentity : Identity[CurrencyRecord, Integer] = {
    Keys.IDENTITY_CURRENCY
  }

  override def getPrimaryKey : UniqueKey[CurrencyRecord] = {
    Keys.KEY_CURRENCY_PRIMARY
  }

  override def getKeys : List[ UniqueKey[CurrencyRecord] ] = {
    return Arrays.asList[ UniqueKey[CurrencyRecord] ](Keys.KEY_CURRENCY_PRIMARY)
  }

  override def getReferences : List[ ForeignKey[CurrencyRecord, _] ] = {
    return Arrays.asList[ ForeignKey[CurrencyRecord, _] ](Keys.CURRENCYCOUNTRYID)
  }

  def country : Country = {
    return new Country(this, Keys.CURRENCYCOUNTRYID)
  }

  override def as(alias : String) : Currency = {
    new Currency(DSL.name(alias), this)
  }

  override def as(alias : Name) : Currency = {
    new Currency(alias, this)
  }

  override def rename(name : String) : Currency = {
    new Currency(DSL.name(name), null)
  }

  override def rename(name : Name) : Currency = {
    new Currency(name, null)
  }
}
