/*
 * This file is generated by jOOQ.
 */
package ch.countryname.countrygame.db.tables


import ch.countryname.countrygame.db.CountryGame
import ch.countryname.countrygame.db.Indexes
import ch.countryname.countrygame.db.Keys
import ch.countryname.countrygame.db.tables.records.ModifierRecord

import java.lang.Class
import java.lang.Double
import java.lang.Integer
import java.lang.String
import java.util.Arrays
import java.util.List

import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Identity
import org.jooq.Index
import org.jooq.Name
import org.jooq.Record
import org.jooq.Schema
import org.jooq.Table
import org.jooq.TableField
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.TableImpl

import scala.Array


object Modifier {

  val MODIFIER = new Modifier
}

class Modifier(
  alias : Name,
  child : Table[_ <: Record],
  path : ForeignKey[_ <: Record, ModifierRecord],
  aliased : Table[ModifierRecord],
  parameters : Array[ Field[_] ]
)
extends TableImpl[ModifierRecord](
  alias,
  CountryGame.COUNTRY_GAME,
  child,
  path,
  aliased,
  parameters,
  DSL.comment("")
)
{

  override def getRecordType : Class[ModifierRecord] = {
    classOf[ModifierRecord]
  }

  val MODIFIERID : TableField[ModifierRecord, Integer] = createField("modifierId", org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), "")

  val MODIFIERNAME : TableField[ModifierRecord, String] = createField("modifierName", org.jooq.impl.SQLDataType.VARCHAR(45).nullable(false), "")

  val MODIFIERVALUE : TableField[ModifierRecord, Double] = createField("modifierValue", org.jooq.impl.SQLDataType.DOUBLE.nullable(false), "")

  def this() = {
    this(DSL.name("modifier"), null, null, null, null)
  }

  def this(alias : String) = {
    this(DSL.name(alias), null, null, ch.countryname.countrygame.db.tables.Modifier.MODIFIER, null)
  }

  def this(alias : Name) = {
    this(alias, null, null, ch.countryname.countrygame.db.tables.Modifier.MODIFIER, null)
  }

  private def this(alias : Name, aliased : Table[ModifierRecord]) = {
    this(alias, null, null, aliased, null)
  }

  def this(child : Table[_ <: Record], key : ForeignKey[_ <: Record, ModifierRecord]) = {
    this(Internal.createPathAlias(child, key), child, key, ch.countryname.countrygame.db.tables.Modifier.MODIFIER, null)
  }

  override def getSchema : Schema = CountryGame.COUNTRY_GAME

  override def getIndexes : List[ Index ] = {
    return Arrays.asList[ Index ](Indexes.MODIFIER_PRIMARY)
  }

  override def getIdentity : Identity[ModifierRecord, Integer] = {
    Keys.IDENTITY_MODIFIER
  }

  override def getPrimaryKey : UniqueKey[ModifierRecord] = {
    Keys.KEY_MODIFIER_PRIMARY
  }

  override def getKeys : List[ UniqueKey[ModifierRecord] ] = {
    return Arrays.asList[ UniqueKey[ModifierRecord] ](Keys.KEY_MODIFIER_PRIMARY)
  }

  override def as(alias : String) : Modifier = {
    new Modifier(DSL.name(alias), this)
  }

  override def as(alias : Name) : Modifier = {
    new Modifier(alias, this)
  }

  override def rename(name : String) : Modifier = {
    new Modifier(DSL.name(name), null)
  }

  override def rename(name : Name) : Modifier = {
    new Modifier(name, null)
  }
}
