/*
 * This file is generated by jOOQ.
 */
package ch.countryname.countrygame.db.tables


import ch.countryname.countrygame.db.CountryGame
import ch.countryname.countrygame.db.Indexes
import ch.countryname.countrygame.db.Keys
import ch.countryname.countrygame.db.tables.records.RelationtypesRecord

import java.lang.Class
import java.lang.Integer
import java.lang.String
import java.util.Arrays
import java.util.List

import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Index
import org.jooq.Name
import org.jooq.Record
import org.jooq.Schema
import org.jooq.Table
import org.jooq.TableField
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.TableImpl

import scala.Array


object Relationtypes {

  val RELATIONTYPES = new Relationtypes
}

class Relationtypes(
  alias : Name,
  child : Table[_ <: Record],
  path : ForeignKey[_ <: Record, RelationtypesRecord],
  aliased : Table[RelationtypesRecord],
  parameters : Array[ Field[_] ]
)
extends TableImpl[RelationtypesRecord](
  alias,
  CountryGame.COUNTRY_GAME,
  child,
  path,
  aliased,
  parameters,
  DSL.comment("")
)
{

  override def getRecordType : Class[RelationtypesRecord] = {
    classOf[RelationtypesRecord]
  }

  val RELATIONTYPEID : TableField[RelationtypesRecord, Integer] = createField("relationTypeId", org.jooq.impl.SQLDataType.INTEGER.nullable(false), "")

  val RELATIONTYPE : TableField[RelationtypesRecord, String] = createField("relationType", org.jooq.impl.SQLDataType.VARCHAR(45).defaultValue(org.jooq.impl.DSL.field("NULL", org.jooq.impl.SQLDataType.VARCHAR)), "")

  val RELATIONTYPEDESCRIPTION : TableField[RelationtypesRecord, String] = createField("relationTypeDescription", org.jooq.impl.SQLDataType.VARCHAR(45).defaultValue(org.jooq.impl.DSL.field("NULL", org.jooq.impl.SQLDataType.VARCHAR)), "")

  def this() = {
    this(DSL.name("relationtypes"), null, null, null, null)
  }

  def this(alias : String) = {
    this(DSL.name(alias), null, null, ch.countryname.countrygame.db.tables.Relationtypes.RELATIONTYPES, null)
  }

  def this(alias : Name) = {
    this(alias, null, null, ch.countryname.countrygame.db.tables.Relationtypes.RELATIONTYPES, null)
  }

  private def this(alias : Name, aliased : Table[RelationtypesRecord]) = {
    this(alias, null, null, aliased, null)
  }

  def this(child : Table[_ <: Record], key : ForeignKey[_ <: Record, RelationtypesRecord]) = {
    this(Internal.createPathAlias(child, key), child, key, ch.countryname.countrygame.db.tables.Relationtypes.RELATIONTYPES, null)
  }

  override def getSchema : Schema = CountryGame.COUNTRY_GAME

  override def getIndexes : List[ Index ] = {
    return Arrays.asList[ Index ](Indexes.RELATIONTYPES_PRIMARY)
  }

  override def getPrimaryKey : UniqueKey[RelationtypesRecord] = {
    Keys.KEY_RELATIONTYPES_PRIMARY
  }

  override def getKeys : List[ UniqueKey[RelationtypesRecord] ] = {
    return Arrays.asList[ UniqueKey[RelationtypesRecord] ](Keys.KEY_RELATIONTYPES_PRIMARY)
  }

  override def as(alias : String) : Relationtypes = {
    new Relationtypes(DSL.name(alias), this)
  }

  override def as(alias : Name) : Relationtypes = {
    new Relationtypes(alias, this)
  }

  override def rename(name : String) : Relationtypes = {
    new Relationtypes(DSL.name(name), null)
  }

  override def rename(name : Name) : Relationtypes = {
    new Relationtypes(name, null)
  }
}
