/*
 * This file is generated by jOOQ.
 */
package ch.countryname.countrygame.db.tables


import ch.countryname.countrygame.db.CountryGame
import ch.countryname.countrygame.db.Indexes
import ch.countryname.countrygame.db.Keys
import ch.countryname.countrygame.db.tables.records.RelationsRecord

import java.lang.Class
import java.lang.Integer
import java.lang.String
import java.util.Arrays
import java.util.List

import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Index
import org.jooq.Name
import org.jooq.Record
import org.jooq.Schema
import org.jooq.Table
import org.jooq.TableField
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.TableImpl

import scala.Array


object Relations {

  val RELATIONS = new Relations
}

class Relations(
  alias : Name,
  child : Table[_ <: Record],
  path : ForeignKey[_ <: Record, RelationsRecord],
  aliased : Table[RelationsRecord],
  parameters : Array[ Field[_] ]
)
extends TableImpl[RelationsRecord](
  alias,
  CountryGame.COUNTRY_GAME,
  child,
  path,
  aliased,
  parameters,
  DSL.comment("")
)
{

  override def getRecordType : Class[RelationsRecord] = {
    classOf[RelationsRecord]
  }

  val RELATIONID : TableField[RelationsRecord, Integer] = createField("relationId", org.jooq.impl.SQLDataType.INTEGER.nullable(false), "")

  val COUNTRYID1 : TableField[RelationsRecord, Integer] = createField("countryId1", org.jooq.impl.SQLDataType.INTEGER.nullable(false), "")

  val RELATIONTYPE : TableField[RelationsRecord, Integer] = createField("relationType", org.jooq.impl.SQLDataType.INTEGER.nullable(false), "")

  def this() = {
    this(DSL.name("relations"), null, null, null, null)
  }

  def this(alias : String) = {
    this(DSL.name(alias), null, null, ch.countryname.countrygame.db.tables.Relations.RELATIONS, null)
  }

  def this(alias : Name) = {
    this(alias, null, null, ch.countryname.countrygame.db.tables.Relations.RELATIONS, null)
  }

  private def this(alias : Name, aliased : Table[RelationsRecord]) = {
    this(alias, null, null, aliased, null)
  }

  def this(child : Table[_ <: Record], key : ForeignKey[_ <: Record, RelationsRecord]) = {
    this(Internal.createPathAlias(child, key), child, key, ch.countryname.countrygame.db.tables.Relations.RELATIONS, null)
  }

  override def getSchema : Schema = CountryGame.COUNTRY_GAME

  override def getIndexes : List[ Index ] = {
    return Arrays.asList[ Index ](Indexes.RELATIONS_COUNTRY1_UNIQUE, Indexes.RELATIONS_PRIMARY, Indexes.RELATIONS_RELATIONTYPEID_IDX)
  }

  override def getPrimaryKey : UniqueKey[RelationsRecord] = {
    Keys.KEY_RELATIONS_PRIMARY
  }

  override def getKeys : List[ UniqueKey[RelationsRecord] ] = {
    return Arrays.asList[ UniqueKey[RelationsRecord] ](Keys.KEY_RELATIONS_PRIMARY, Keys.KEY_RELATIONS_COUNTRY1_UNIQUE)
  }

  override def getReferences : List[ ForeignKey[RelationsRecord, _] ] = {
    return Arrays.asList[ ForeignKey[RelationsRecord, _] ](Keys.COUNTRYID, Keys.RELATIONTYPEID)
  }

  def country : Country = {
    return new Country(this, Keys.COUNTRYID)
  }

  def relationtypes : Relationtypes = {
    return new Relationtypes(this, Keys.RELATIONTYPEID)
  }

  override def as(alias : String) : Relations = {
    new Relations(DSL.name(alias), this)
  }

  override def as(alias : Name) : Relations = {
    new Relations(alias, this)
  }

  override def rename(name : String) : Relations = {
    new Relations(DSL.name(name), null)
  }

  override def rename(name : Name) : Relations = {
    new Relations(name, null)
  }
}
