/*
 * This file is generated by jOOQ.
 */
package ch.countryname.countrygame.db.tables.records


import ch.countryname.countrygame.db.tables.Manpower

import java.lang.Double
import java.lang.Integer

import org.jooq.Field
import org.jooq.Record1
import org.jooq.Record4
import org.jooq.Row4
import org.jooq.impl.UpdatableRecordImpl


class ManpowerRecord extends UpdatableRecordImpl[ManpowerRecord](Manpower.MANPOWER) with Record4[Integer, Double, Double, Integer] {

  def setManpowerid(value : Integer) : Unit = {
    set(0, value)
  }

  def getManpowerid : Integer = {
    val r = get(0)
    if (r == null) null else r.asInstanceOf[Integer]
  }

  def setManpowertype(value : Double) : Unit = {
    set(1, value)
  }

  def getManpowertype : Double = {
    val r = get(1)
    if (r == null) null else r.asInstanceOf[Double]
  }

  def setManpowernumber(value : Double) : Unit = {
    set(2, value)
  }

  def getManpowernumber : Double = {
    val r = get(2)
    if (r == null) null else r.asInstanceOf[Double]
  }

  def setCountryid(value : Integer) : Unit = {
    set(3, value)
  }

  def getCountryid : Integer = {
    val r = get(3)
    if (r == null) null else r.asInstanceOf[Integer]
  }

  // -------------------------------------------------------------------------
  // Primary key information
  // -------------------------------------------------------------------------
  override def key : Record1[Integer] = {
    return super.key.asInstanceOf[ Record1[Integer] ]
  }

  // -------------------------------------------------------------------------
  // Record4 type implementation
  // -------------------------------------------------------------------------

  override def fieldsRow : Row4[Integer, Double, Double, Integer] = {
    super.fieldsRow.asInstanceOf[ Row4[Integer, Double, Double, Integer] ]
  }

  override def valuesRow : Row4[Integer, Double, Double, Integer] = {
    super.valuesRow.asInstanceOf[ Row4[Integer, Double, Double, Integer] ]
  }
  override def field1 : Field[Integer] = Manpower.MANPOWER.MANPOWERID
  override def field2 : Field[Double] = Manpower.MANPOWER.MANPOWERTYPE
  override def field3 : Field[Double] = Manpower.MANPOWER.MANPOWERNUMBER
  override def field4 : Field[Integer] = Manpower.MANPOWER.COUNTRYID
  override def component1 : Integer = getManpowerid
  override def component2 : Double = getManpowertype
  override def component3 : Double = getManpowernumber
  override def component4 : Integer = getCountryid
  override def value1 : Integer = getManpowerid
  override def value2 : Double = getManpowertype
  override def value3 : Double = getManpowernumber
  override def value4 : Integer = getCountryid

  override def value1(value : Integer) : ManpowerRecord = {
    setManpowerid(value)
    this
  }

  override def value2(value : Double) : ManpowerRecord = {
    setManpowertype(value)
    this
  }

  override def value3(value : Double) : ManpowerRecord = {
    setManpowernumber(value)
    this
  }

  override def value4(value : Integer) : ManpowerRecord = {
    setCountryid(value)
    this
  }

  override def values(value1 : Integer, value2 : Double, value3 : Double, value4 : Integer) : ManpowerRecord = {
    this.value1(value1)
    this.value2(value2)
    this.value3(value3)
    this.value4(value4)
    this
  }

  def this(manpowerid : Integer, manpowertype : Double, manpowernumber : Double, countryid : Integer) = {
    this()

    set(0, manpowerid)
    set(1, manpowertype)
    set(2, manpowernumber)
    set(3, countryid)
  }
}
