/*
 * This file is generated by jOOQ.
 */
package ch.countryname.countrygame.db.tables.records


import ch.countryname.countrygame.db.tables.Manpower

import java.lang.Integer

import org.jooq.Field
import org.jooq.Record1
import org.jooq.Record2
import org.jooq.Row2
import org.jooq.impl.UpdatableRecordImpl


class ManpowerRecord extends UpdatableRecordImpl[ManpowerRecord](Manpower.MANPOWER) with Record2[Integer, Integer] {

  def setManpowerid(value : Integer) : Unit = {
    set(0, value)
  }

  def getManpowerid : Integer = {
    val r = get(0)
    if (r == null) null else r.asInstanceOf[Integer]
  }

  def setManpowernumber(value : Integer) : Unit = {
    set(1, value)
  }

  def getManpowernumber : Integer = {
    val r = get(1)
    if (r == null) null else r.asInstanceOf[Integer]
  }

  // -------------------------------------------------------------------------
  // Primary key information
  // -------------------------------------------------------------------------
  override def key : Record1[Integer] = {
    return super.key.asInstanceOf[ Record1[Integer] ]
  }

  // -------------------------------------------------------------------------
  // Record2 type implementation
  // -------------------------------------------------------------------------

  override def fieldsRow : Row2[Integer, Integer] = {
    super.fieldsRow.asInstanceOf[ Row2[Integer, Integer] ]
  }

  override def valuesRow : Row2[Integer, Integer] = {
    super.valuesRow.asInstanceOf[ Row2[Integer, Integer] ]
  }
  override def field1 : Field[Integer] = Manpower.MANPOWER.MANPOWERID
  override def field2 : Field[Integer] = Manpower.MANPOWER.MANPOWERNUMBER
  override def component1 : Integer = getManpowerid
  override def component2 : Integer = getManpowernumber
  override def value1 : Integer = getManpowerid
  override def value2 : Integer = getManpowernumber

  override def value1(value : Integer) : ManpowerRecord = {
    setManpowerid(value)
    this
  }

  override def value2(value : Integer) : ManpowerRecord = {
    setManpowernumber(value)
    this
  }

  override def values(value1 : Integer, value2 : Integer) : ManpowerRecord = {
    this.value1(value1)
    this.value2(value2)
    this
  }

  def this(manpowerid : Integer, manpowernumber : Integer) = {
    this()

    set(0, manpowerid)
    set(1, manpowernumber)
  }
}
